name: PingFederate Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'deploy'
        type: choice
        options:
        - deploy
        - delete

variables:
  JDK_URL: "https://vijay101.blob.core.windows.net/storage/jdk-11.0.20_linux-x64_bin.tar.gz"
  PF_URL: "https://vijay101.blob.core.windows.net/storage/pingfederate-12.2.0.zip"
  JDK_FILENAME: "jdk-11.0.20_linux-x64_bin.tar.gz"
  PF_FILENAME: "pingfederate-12.2.0.zip"
  INSTALL_DIR: "/datadrive/pingdevops"
  JAVA_DIR: "/datadrive/pingdevops/jdk"
  PF_DIR: "/datadrive/pingdevops"

jobs:
  deploy:
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download JDK and PingFederate
      run: |
        echo "Downloading JDK..."
        curl -o ${{ env.JDK_FILENAME }} ${{ env.JDK_URL }}

        echo "Downloading PingFederate..."
        curl -o ${{ env.PF_FILENAME }} ${{ env.PF_URL }}

    - name: Copy files to Linux server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ${{ env.JDK_FILENAME }},${{ env.PF_FILENAME }}
        target: /tmp

    - name: Install JDK & PingFederate and Start Server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Creating install directory if not exists..."
          sudo mkdir -p ${{ env.INSTALL_DIR }}
          sudo chmod -R 755 ${{ env.INSTALL_DIR }}

          echo "Extracting JDK..."
          sudo tar -xzf /tmp/${{ env.JDK_FILENAME }} -C ${{ env.INSTALL_DIR }}
          JDK_EXTRACTED_DIR=$(tar -tf /tmp/${{ env.JDK_FILENAME }} | head -1 | cut -f1 -d"/")
          sudo mv ${{ env.INSTALL_DIR }}/$JDK_EXTRACTED_DIR ${{ env.JAVA_DIR }}

          echo "Setting JAVA_HOME in .bashrc..."
          echo "export JAVA_HOME=${{ env.JAVA_DIR }}" | sudo tee -a /etc/profile
          echo "export PATH=\$JAVA_HOME/bin:\$PATH" | sudo tee -a /etc/profile
          source /etc/profile

          echo "Unzipping PingFederate..."
          sudo unzip -o /tmp/${{ env.PF_FILENAME }} -d ${{ env.INSTALL_DIR }}

          echo "Starting PingFederate..."
          export JAVA_HOME=${{ env.JAVA_DIR }}
          ${{ env.PF_DIR }}/pingfederate-12.2.0/pingfederate/sbin/pingfederate-run.sh

          echo "Deployment complete."

  delete:
    if: github.event.inputs.action == 'delete'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Stop PingFederate and Delete Installation
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Stopping PingFederate..."
          pkill -f pingfederate

          echo "Removing installation directory..."
          sudo rm -rf ${{ env.INSTALL_DIR }}

          echo "Removing JDK and PingFederate files from /tmp..."
          sudo rm -f /tmp/${{ env.JDK_FILENAME }}
          sudo rm -f /tmp/${{ env.PF_FILENAME }}

          echo "Deployment deleted."
