trigger:
- main

variables:
  storageAccount: 'ramanstorage2025'
  containerName: 'storage'
  jdkBlobName: 'jdk-11.0.20_linux-x64_bin.tar.gz'
  pfBlobName: 'pingfederate-12.2.0.zip'
  downloadPath: '$(Pipeline.Workspace)/downloads'
  remotePath: '/root/pfdeploy'  # adjust remote user path
  installPath: '/datadrive/pingfederate'
  sasToken: 'sv=2024-11-04&ss=bfqt&srt=c&sp=rwdlacupiytfx&se=2026-05-08T21:34:48Z&st=2025-04-05T13:34:48Z&spr=https&sig=pyNG%2BbVken4ueceSu1Z311DYOXOwLtifHr7JriwNcdw%3D'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployPingFederate
  jobs:
  - job: DownloadAndDeploy
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'pfdockerpoc_sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          mkdir -p $(downloadPath)
          az storage blob download --account-name $(storageAccount) --container-name $(containerName) --name $(jdkBlobName) --file "$(downloadPath)/$(jdkBlobName)" --sas-token "$(sasToken)"
          az storage blob download --account-name $(storageAccount) --container-name $(containerName) --name $(pfBlobName) --file "$(downloadPath)/$(pfBlobName)" --sas-token "$(sasToken)"
      displayName: 'Download JDK and PingFederate from Azure Blob Storage'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'pfdockerpoc_sc'
        sourceFolder: '$(downloadPath)'
        contents: '**'
        targetFolder: '$(remotePath)'
      displayName: 'Copy files to remote server'

    - task: SSH@0
      inputs:
        sshEndpoint: 'pfdockerpoc_sc'
        runOptions: 'commands'
        command: |
          echo "Installing JDK..."
          sudo mkdir -p /datadrive/jdk
          sudo tar -xzf $(remotePath)/$(jdkBlobName) -C /datadrive/jdk --strip-components=1
          echo 'export JAVA_HOME=/datadrive/jdk' | sudo tee -a /etc/profile
          echo 'export PATH=$JAVA_HOME/bin:$PATH' | sudo tee -a /etc/profile
          source /etc/profile

          echo "Installing PingFederate..."
          sudo mkdir -p $(installPath)
          sudo unzip -q $(remotePath)/$(pfBlobName) -d $(installPath)

          echo "Starting PingFederate..."
          sudo nohup $(installPath)/pingfederate/sbin/pingfederate-run.sh > $(installPath)/pingfederate/logs/start.log 2>&1 &
          sleep 10
          tail -n 20 $(installPath)/pingfederate/logs/server.log || true
      displayName: 'Install and Start PingFederate on Remote Server'
